export const knowledgeBaseConstants = {
  GET_KNOWLEDGE_BASES_REQUEST: 'GET_KNOWLEDGE_BASES_REQUEST',
  GET_KNOWLEDGE_BASES_SUCCESS: 'GET_KNOWLEDGE_BASES_SUCCESS',
  GET_KNOWLEDGE_BASES_FAILURE: 'GET_KNOWLEDGE_BASES_FAILURE',

  CREATE_KNOWLEDGE_BASE_REQUEST: 'CREATE_KNOWLEDGE_BASE_REQUEST',
  CREATE_KNOWLEDGE_BASE_SUCCESS: 'CREATE_KNOWLEDGE_BASE_SUCCESS',
  CREATE_KNOWLEDGE_BASE_FAILURE: 'CREATE_KNOWLEDGE_BASE_FAILURE',

  DELETE_KNOWLEDGE_BASE_REQUEST: 'DELETE_KNOWLEDGE_BASE_REQUEST',
  DELETE_KNOWLEDGE_BASE_SUCCESS: 'DELETE_KNOWLEDGE_BASE_SUCCESS',
  DELETE_KNOWLEDGE_BASE_FAILURE: 'DELETE_KNOWLEDGE_BASE_FAILURE',

  IMPORT_FILE_REQUEST: 'IMPORT_FILE_REQUEST',
  IMPORT_FILE_SUCCESS: 'IMPORT_FILE_SUCCESS',
  IMPORT_FILE_FAILURE: 'IMPORT_FILE_FAILURE',

  GET_KNOWLEDGE_BASE_FILES_REQUEST: 'GET_KNOWLEDGE_BASE_FILES_REQUEST',
  GET_KNOWLEDGE_BASE_FILES_SUCCESS: 'GET_KNOWLEDGE_BASE_FILES_SUCCESS',
  GET_KNOWLEDGE_BASE_FILES_FAILURE: 'GET_KNOWLEDGE_BASE_FILES_FAILURE',

  DELETE_FILE_FROM_KB_REQUEST: 'DELETE_FILE_FROM_KB_REQUEST',
  DELETE_FILE_FROM_KB_SUCCESS: 'DELETE_FILE_FROM_KB_SUCCESS',
  DELETE_FILE_FROM_KB_FAILURE: 'DELETE_FILE_FROM_KB_FAILURE',

  IMPORT_TYPE_FILE: 'file',
  IMPORT_TYPE_URL: 'url',

  FILE_TYPE_PDF: 'pdf',
  FILE_TYPE_RTF: 'rtf',
}
