export const teamContants = {
  GET_TEAMS_REQUEST: 'GET_TEAMS_REQUEST',
  GET_TEAMS_SUCCESS: 'GET_TEAMS_SUCCESS',
  GET_TEAMS_FAILED: 'GET_TEAMS_FAILED',
  RESET_TEAMS: 'RESET_TEAMS',

  GET_TEAM_MEMBERS_REQUEST: 'GET_TEAM_MEMBERS_REQUEST',
  GET_TEAM_MEMBERS_SUCCESS: 'GET_TEAM_MEMBERS_SUCCESS',
  GET_TEAM_MEMBERS_FAILED: 'GET_TEAM_MEMBERS_FAILED',
  RESET_TEAM_MEMBERS: 'RESET_TEAM_MEMBERS',

  GET_ALL_TEAMS_REQUEST: 'GET_ALL_TEAMS_REQUEST',
  GET_ALL_TEAMS_SUCCESS: 'GET_ALL_TEAMS_SUCCESS',
  GET_ALL_TEAMS_FAILED: 'GET_ALL_TEAMS_FAILED',
  RESET_ALL_TEAMS: 'RESET_ALL_TEAMS',

  SHOW_CREATE_MODAL: 'SHOW_CREATE_MODAL',
  HIDE_CREATE_MODAL: 'HIDE_CREATE_MODAL',
  UPDATE_CREATE_DATA: 'UPDATE_CREATE_DATA',
  RESET_CREATE_DATA: 'RESET_CREATE_DATA',

  CREATING_TEAM: 'CREATING_TEAM',
  CREATE_TEAM_SUCCESS: 'CREATE_TEAM_SUCCESS',
  CREATE_TEAM_FAILED: 'CREATE_TEAM_FAILED',

  SHOW_JOIN_MODAL: 'SHOW_JOIN_MODAL',
  HIDE_JOIN_MODAL: 'HIDE_JOIN_MODAL',

  JOIN_TEAM_REQUEST: 'JOIN_TEAM_REQUEST',
  JOIN_TEAM_SUCCESS: 'JOIN_TEAM_SUCCESS',
  JOIN_TEAM_FAILED: 'JOIN_TEAM_FAILED',

  LEAVE_TEAM_REQUEST: 'LEAVE_TEAM_REQUEST',
  LEAVE_TEAM_SUCCESS: 'LEAVE_TEAM_SUCCESS',
  LEAVE_TEAM_FAILED: 'LEAVE_TEAM_FAILED',

  ADD_TEAM_MEMBER_REQUEST: 'ADD_TEAM_MEMBER_REQUEST',
  ADD_TEAM_MEMBER_SUCCESS: 'ADD_TEAM_MEMBER_SUCCESS',
  ADD_TEAM_MEMBER_FAILED: 'ADD_TEAM_MEMBER_FAILED',

  TRANSFER_TEAM_REQUEST: 'TRANSFER_TEAM_REQUEST',
  TRANSFER_TEAM_SUCCESS: 'TRANSFER_TEAM_SUCCESS',
  TRANSFER_TEAM_FAILED: 'TRANSFER_TEAM_FAILED',
  SHOW_TRANSFER_TEAM_MODAL: 'SHOW_TRANSFER_TEAM_MODAL',
  HIDE_TRANSFER_TEAM_MODAL: 'HIDE_TRANSFER_TEAM_MODAL',

  SHOW_ADD_TEAM_MEMBER_MODAL: 'SHOW_ADD_TEAM_MEMBER_MODAL',
  HIDE_ADD_TEAM_MEMBER_MODAL: 'HIDE_ADD_TEAM_MEMBER_MODAL',

  SHOW_ADD_DEPT_MEMBER_MODAL: 'SHOW_ADD_DEPT_MEMBER_MODAL',
  HIDE_ADD_DEPT_MEMBER_MODAL: 'HIDE_ADD_DEPT_MEMBER_MODAL',

  ADD_DEPARTMENT_REQUEST: 'ADD_DEPARTMENT_REQUEST',
  ADD_DEPARTMENT_SUCCESS: 'ADD_DEPARTMENT_SUCCESS',
  ADD_DEPARTMENT_FAILED: 'ADD_DEPARTMENT_FAILED',

  SHOW_ADD_DEPARTMENT_MODAL: 'SHOW_ADD_DEPARTMENT_MODAL',
  HIDE_ADD_DEPARTMENT_MODAL: 'HIDE_ADD_DEPARTMENT_MODAL',
  UPDATE_ADD_DEPARTMENT_DATA: 'UPDATE_ADD_DEPARTMENT_DATA',

  ADD_DEPARTMENT_MEMEBER_REQUEST: 'ADD_DEPARTMENT_MEMEBER_REQUEST',
  ADD_DEPARTMENT_MEMEBER_SUCCESS: 'ADD_DEPARTMENT_MEMEBER_SUCCESS',
  ADD_DEPARTMENT_MEMEBER_FAILED: 'ADD_DEPARTMENT_MEMEBER_FAILED',

  SHOW_ADD_DEPARTMENT_MEMEBER_MODAL: 'SHOW_ADD_DEPARTMENT_MEMEBER_MODAL',
  HIDE_ADD_DEPARTMENT_MEMEBER_MODAL: 'HIDE_ADD_DEPARTMENT_MEMEBER_MODAL'
}
