export const userConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',

  AUTH_STATE_UNKNOWN: 0,
  AUTH_STATE_REQUEST: 1,
  AUTH_STATE_FAILURE: 2,
  AUTH_STATE_SUCCESS: 3,

  LOGOUT: 'USERS_LOGOUT',

  TOKEN_STORAGE_KEY: 'SHIMO_SDK_DEMO_TOKEN',
  LOGIN_KEY: 'LOGIN_KEY',

  ACCESS_TOKEN_KEY: 'accessToken',

  REDIRECT_URL_KEY: 'redirect',

  LANGUAGE_MODAL_SHOW: 'LANGUAGE_MODAL_SHOW',
  LANGUAGE_MODAL_HIDDEN: 'LANGUAGE_MODAL_HIDDEN',

  LANGUAGE_STORAGE_KEY: 'SHIMO_SDK_LANG',
  LANGUAGE_INITED: 'LANGUAGE_INITED',
  LANGUAGE_CHANGED: 'LANGUAGE_CHANGED',

  LANGUAGE_LOCAL: 'local',
  LANGUAGE_ZH_CN: 'zh-CN',
  LANGUAGE_EN: 'en',
  LANGUAGE_JA: 'ja',
  LANGUAGE_AR_SA: 'ar-SA'
}
